kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-cam
  namespace: edge-cam
  labels:
    app: edge-cam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-cam
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edge-cam
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      serviceAccountName: edge-cam
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: edge-cam
          env:        
            - name: WS_PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-cam
                  key: WS_PORT
            - name: STREAM_PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-cam
                  key: STREAM_PORT
            - name: VIDEO_PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-cam
                  key: VIDEO_PORT
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/edge-cam:latest
          volumeMounts:
            - name: hostpath-dev
              mountPath: /dev
      volumes:
        - name: hostpath-dev
          hostPath:
              path: /dev
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600